### PR TITLE
Changes made to CP, TRW + added Workshop 

### PR DESCRIPTION
**Pull request by SivaaB**
Heyo, pls go over the changes I've made and accept PR If it fits the bag. To quickly summarize the changes I've made so far are: 

CP --> You had not connected your notes MD files to the main MD File, I fixed that minor inconvenience. I also added the link to my repo containing solutions to all the tut and practical sheets. As for notes, you've already covered all topics up until midsem so that's sorted. I shall add notes for post midsem as we progress through this semester. 

TRW --> There was a folder called "slides" which did not contain all the PPTs, I added the rest covering syllabus for the entire coursework. I also managed to add my notes (which I used for my exam today lol) for both parts of the midsem paper, go over them and let me know if that format is acceptable. 

EG --> This was a quick add to the 1_Core folder, I made two sub folders, one containing the link to all the demonstrations in workshop which helps during comprehensive exams and one containing my midsem notes. 

This is my first time creating a pull request and what not, feel free to point out mistakes.

### CODE REVIEW

**Comment by AhmedThahir** [comment]
Nice job Sivaa! ✨

Regarding

> You had not connected your notes MD files to the main MD File

In order to reduce redundancy, I have not added that. The navigation bar allows the user to go through each page. If you really want every main course file to contain links to other pages, create a new issue.

**Comment by SivaaB** [comment]
Oh yea, my bad totally looked over the nav bar. 
Thank you.  :)

**Comment by AhmedThahir** [comment]
So what is your thoughts? Navbar is sufficient?

If you added for the other courses, you may remove them.

**Comment by SivaaB** [comment]
Nav bar is more than sufficient and yes, I need to make appropriate changes for other courses as well. Will probably go on a commit spree coming Monday night (midsems end that day for me). Thinking of adding some other stuff for EG, Biology Lab, Chem Lab, Phy Lab, Gen Bio on the same night as well.

**Comment by AhmedThahir** [comment]
Cool that's great!

Just make sure they're in **markdown format**. This is to ensure text-based and future-proofing this knowledge without depending on Microsoft or any other company to access the notes.

**Pull request merged**
